server:
  port: 80
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
    jdbc-type-for-null: NULL
spring:
  main:
      allow-bean-definition-overriding: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  serialization:
    fail-on-empty-beans: false
  devtools:
    livereload:
      enabled: true
  h2:
    console:
      enabled: true
      path: /spendMoney_db
  datasource:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:h2:~/spendMoney_db
      #driver-class-name: org.h2.Driver
      #jdbc-url: jdbc:h2:~/spendMoney_db;AUTO_SERVER=TRUE
      username: test
      password: 1234
  data:
    rest:
      basePath: /
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp